// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXvKLR7fLchbiTtHdrCGbYzXZ6aMABuTg',
    appId: '1:1069745556431:web:4fdf9d1379a42d362fe0ba',
    messagingSenderId: '1069745556431',
    projectId: 'stripesafepay',
    authDomain: 'stripesafepay.firebaseapp.com',
    storageBucket: 'stripesafepay.appspot.com',
    measurementId: 'G-BKPS13ZVR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuYa-BI-Cd0lOBfG3xJR1o5Ptc5pJ6Ykg',
    appId: '1:1069745556431:android:2149d128daf7592e2fe0ba',
    messagingSenderId: '1069745556431',
    projectId: 'stripesafepay',
    storageBucket: 'stripesafepay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0nE_sxiNCN_ojcBalgzTm9rl5wRVNxag',
    appId: '1:1069745556431:ios:ea256ecea6c3195b2fe0ba',
    messagingSenderId: '1069745556431',
    projectId: 'stripesafepay',
    storageBucket: 'stripesafepay.appspot.com',
    iosClientId: '1069745556431-lp5ptofhn86q3imijdemlej62knola6v.apps.googleusercontent.com',
    iosBundleId: 'com.artasce.stripesafepay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0nE_sxiNCN_ojcBalgzTm9rl5wRVNxag',
    appId: '1:1069745556431:ios:ea256ecea6c3195b2fe0ba',
    messagingSenderId: '1069745556431',
    projectId: 'stripesafepay',
    storageBucket: 'stripesafepay.appspot.com',
    iosClientId: '1069745556431-lp5ptofhn86q3imijdemlej62knola6v.apps.googleusercontent.com',
    iosBundleId: 'com.artasce.stripesafepay',
  );
}
